name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - testenv2
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    # 只在 push / 手动触发时部署 named environment
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: cjk7989/staticstiesactionoryx@jikunswa4
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_FLOWER_0DD753A00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "."
          api_location: ""
          output_location: ""
          deployment_environment: "testenv2"
          verbose: true
